random_forest:
  max_features: 2500
  min_df: 10
#  n_estimators: 12
  n_estimators: 804
  max_depth: 156
  min_samples_leaf: 1
  min_samples_split: 16

lstm:
  input_len: 100
  lstm_size: 128
  embedding_size: 64
  dropout_rate: 0.3
  activation_out: sigmoid
  leraning_rate: 0.01
  loss: binary_crossentropy
  metric: acc
  batch: 128
  epoch: 8
  verbose: 1

lstm2:
  input_len: 100
  lstm_size: 128
  embedding_size: 300
  dropout_rate: 0.5
  activation_out: sigmoid
  leraning_rate: 0.01
  loss: binary_crossentropy
  metric: acc
  batch: 128
  epoch: 5
  verbose: 1
  recurrent_dropout: 0.3

fast_text:
  text_col: text
  label: label
  max_features: 5000
  max_len: 500
  verbose: 1
  max_epoch: 3
  learning_rate: 0.01
  n_cycles: 3
  cycle_len: 2
  cycle_mult: 2

bert:
  text_col: text
  label_col: label
  max_features: 30000
  max_len: 500
  verbose: 1
  pre_trained: bert
  batch: 6
  max_epoch: 1
  n_cycles: 3
  cycle_len: 1
  cycle_mult: 1